name = "simple_http"
version = "0.1.0"
description = "Simple HTTP client to power API wrappers written in Gleam"

licences = ["Apache-2.0"]
repository = { type = "github", user = "HarryET", repo = "simple_http" }
links = [
    { title = "Website", href= "https://hexdocs.pm/simple_http" },
    { title = "Sponsor", href = "https://github.com/sponsors/HarryET" }
]

[dependencies]
gleam_stdlib = "~> 0.26"
gleam_http = "~> 3.1"


[dev-dependencies]
gleeunit = "~> 0.9"
